### ISSUE TITLE
Offset Support

### ISSUE THREAD

**Issue by LukeAbell** [cerbero90/lazy-json-pages#3]
Any plans to support offset based pagination in the future? One of the APIs we're working with requires you to pass a `start` number and paginate by offset vs passing a page number.

Thanks!

**Comment by cerbero90** [comment]
Hi @LukeAbell, offset is in the roadmap for the next release :)

Just to be on the same page, you mean something like this, right?

https://pokeapi.co/docs/v2#resource-listspagination-section

**Comment by LukeAbell** [comment]
@cerbero90 awesome! Yep, exactly like that.

**Comment by cerbero90** [comment]
@LukeAbell offset is now supported in Lazy JSON Pages v2 🎉

**Comment by LukeAbell** [comment]
@cerbero90 Thank you!!
